config/routes.rb
Rails.application.routes.draw do

  scope "/:locale" do
      namespace :dashboard do
        resources :decks
        resources :cards
        resources :home, only:[:index, :check]
      end
      namespace :home do
        resources :users
        resources :sessions, only: [:new, :create, :destroy]
      end
  end
  get 'oauths/oauth'

  get 'oauths/callback'


  root "dashboard/home#index"

  get 'logout' => 'home/sessions#destroy', as: 'logout'
  get 'login' => 'home/sessions#new', as: 'login'
  get 'signup' => 'home/users#new', as: 'signup'
  post 'login' => 'home/sessions#new'
  patch 'home' => 'home#check'
  get 'home', to: 'dashboard/home#index', defaults: { format: :json }
  post 'home', to: 'dashboard/home#check', defaults: { format: :json }
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callbck' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  belongs_to :deck
  before_validation {original_text.downcase!}
  before_validation {translated_text.downcase!}
  before_create :set_review_date
  validates :original_text, :translated_text, presence: true
  validate :original_text_not_equal_translated_text
  scope :random_card, ->{ where("review_date <= ?", DateTime.now ).order("RANDOM()").limit(1) }
  has_attached_file :image,
                    styles: {medium: "360x360"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  def original_text_not_equal_translated_text
    errors.add(:original_text, "Original text not equal translated") if original_text == translated_text
  end

  def set_review_date
    date = DateTime.now
    self.review_date = date
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_current_card, only: [:show, :edit, :update, :destroy]
  before_action :current_user_card
  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id
    if @card.save
      redirect_to cards_path, :notice => t('flash_messages.card.new_card')
    else
      redirect_to new_card_path,:notice => t('flash_messages.card.error_card')
    end
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path, :notice => t('flash_messages.card.update_card')
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path, :notice => t('flash_messages.card.del_card')
  end

  private
    def current_user_card
      @cards = current_user.cards
    end
    def set_current_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date, :image, :deck_id)
    end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  before_action :set_current_card, only: [:show, :edit, :update, :destroy]
  before_action :current_user_card
  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id
    if @card.save
      redirect_to dashboard_cards_path, notice: t('flash_messages.card.new_card')
    else
      redirect_to new_dashboard_card_path, notice: t('flash_messages.card.error_card')
    end
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to dashboard_cards_path, notice: t('flash_messages.card.update_card')
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to dashboard_cards_path, notice: t('flash_messages.card.del_card')
  end

  private
    def current_user_card
      @cards = current_user.cards && Card.where(user_id: nil)
    end
    def set_current_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date, :image, :deck_id)
    end
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
    <% if flash[:notice] %>
        <div class='alert alert-info alert-danger'>
          <% for message in @card.errors.full_messages %>
              <li><%= message %></li>
          <% end %>
        </div>
    <% end %>
    <%= f.input :original_text %>
    <%= f.input :translated_text%>
    <%= f.input :review_date %>
    <%= f.association :deck %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, class:"btn btn-lg btn-success btn-block"%>
<% end %>

app/views/cards/index.html.erb
<% if flash[:notice] %>
    <div class='alert alert-info '>
      <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name %>
      <% end -%>
    </div>
<% end %>
<h1><%= t('all_cards.all_cards') %></h1>
<table class="table table-striped" id="cards-table">
  <tr>
    <th><%= t('all_cards.original_text') %></th>
    <th><%= t('all_cards.translated_text') %></th>
    <th><%= t('all_cards.review_date') %></th>
    <th><%= t('all_cards.edit_card') %></th>
    <th><%= t('all_cards.delete_card') %></th>
  </tr>

  <% @cards.each do |card| %>
      <tr>
        <td><%= card.original_text %></td>
        <td><%= card.translated_text %></td>
        <td><%= card.review_date.strftime("%d/%m/%Y") %></td>

          <td><%= link_to t('all_cards.edit_card'), edit_card_path(card) %></td>
          <td><%= link_to t('all_cards.delete_card'), card_path(card.id),
                          method: :delete,
                          data: { confirm: t('all_cards.confirm') } %></td>
          <% end %>
      </tr>
</table>