config/routes.rb
Rails.application.routes.draw do

  scope "/:locale" do
      namespace :dashboard do
        resources :decks
        resources :cards
        resources :home, only:[:index, :check]
      end
      namespace :home do
        resources :users
        resources :sessions, only: [:new, :create, :destroy]
      end
  end
  get 'oauths/oauth'

  get 'oauths/callback'


  root "dashboard/home#index"

  get 'logout' => 'home/sessions#destroy', as: 'logout'
  get 'login' => 'home/sessions#new', as: 'login'
  get 'signup' => 'home/users#new', as: 'signup'
  post 'login' => 'home/sessions#new'
  patch 'home' => 'home#check'
  get 'home', to: 'dashboard/home#index', defaults: { format: :json }
  post 'home', to: 'dashboard/home#check', defaults: { format: :json }
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callbck' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :users
  has_many :cards
  scope :active_deck, ->{ where(active: true).first }
  validates :name, presence: true
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  before_action :set_current_card, only: [:show, :edit, :update, :destroy]
  before_action :current_user_card
  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id
    if @card.save
      redirect_to dashboard_cards_path, notice: t('flash_messages.card.new_card')
    else
      redirect_to new_dashboard_card_path, notice: t('flash_messages.card.error_card')
    end
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to dashboard_cards_path, notice: t('flash_messages.card.update_card')
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to dashboard_cards_path, notice: t('flash_messages.card.del_card')
  end

  private
    def current_user_card
      @cards = current_user.cards && Card.where(user_id: nil)
    end
    def set_current_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date, :image, :deck_id)
    end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  before_action :set_current_deck, only: [:show, :edit, :update, :destroy]
  before_action :current_user_decks

  def index
  end

  def show
  end

  def new
    @deck = Deck.new
  end
  def create
    @deck = Deck.new(deck_params)
    @deck.user_id = current_user.id
    check_active_deck
    if @deck.save
      redirect_to dashboard_decks_path, notice: t('flash_messages.deck.new_deck')
    else
      render :new
    end
  end

  def edit
  end

  def update
    check_active_deck
    if @deck.update(deck_params)

      redirect_to dashboard_decks_path, notice: t('flash_messages.deck.update_deck')
    else
      render 'edit'
    end
  end

  def destroy
    @deck.destroy
    redirect_to dashboard_decks_path, notice: t('flash_messages.deck.del_deck')
  end


  private
    def check_active_deck
      if @deck.active == true
        @decks.update_all(active: false)
      end
    end

    def current_user_decks
      @decks = current_user.decks
    end

    def set_current_deck
      @deck = Deck.find(params[:id])
    end

    def deck_params
      params.require(:deck).permit(:name, :active)
    end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:check]

  def index
    result = GetRandomCard.call(user: current_user)
    @card = result.card
    if @card
      gon.card_id = @card.id
    else
      gon.card_id = 0
    end
    respond_to do |format|
      format.html
      format.json { render json: { card: @card }}
    end
  end

  def show
  end

  def check
   checked_card = CheckCard.call(card_id: params[:card_id],
                   original_text: params[:check_text],
                   timer: params[:timer])
   @notice = checked_card.message
   nominate = GetRandomCard.call(user: current_user)

   @card =nominate.card
   respond_to do |format|
     format.html
     format.json { render json: { notice: @notice }}
   end
  end


  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date, :image,:timer)
    end

    def deck_params
      params.require(:deck).permit(:user_id, :name, :active)
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_current_deck, only: [:show, :edit, :update, :destroy]
  before_action :current_user_decks

  def index
  end

  def show
  end

  def new
    @deck = Deck.new
  end
  def create
    @deck = Deck.new(deck_params)
    @deck.user_id = current_user.id
    check_active_deck
    if @deck.save
      redirect_to decks_path, :notice => t('flash_messages.deck.new_deck')
    else
      render :new
    end
  end

  def edit
  end

  def update
    check_active_deck
    if @deck.update(deck_params)

      redirect_to decks_path, :notice => t('flash_messages.deck.update_deck')
    else
      render 'edit'
    end
  end

  def destroy
    @deck.destroy
    redirect_to decks_path, :notice => t('flash_messages.deck.del_deck')
  end


  private
    def check_active_deck
      if @deck.active == true
        @decks.update_all(active: false)
      end
    end

    def current_user_decks
      @decks = current_user.decks
    end

    def set_current_deck
      @deck = Deck.find(params[:id])
    end

    def deck_params
      params.require(:deck).permit(:name, :active)
    end
end

app/views/dashboard/decks/_form.html.erb
<%= simple_form_for @deck, url:{ controller: 'decks' } do|f| %>
  <%= f.input :name %>
  <%= f.input :active, as: :radio_buttons %>
  <%= f.button :submit, class:"btn btn-lg btn-success btn-block" %>
<% end %>

app/views/dashboard/decks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-push-3 text-center ">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1><%= t('deck.edit_card') %></h1>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/decks/index.html.erb
<% if flash[:notice] %>
    <div class='alert alert-info'>
      <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name %>
      <% end -%>
    </div>
<% end %>
<h1><%= t('all_decks.all_decks') %></h1>
<table class="table table-striped">
  <tr>
    <th><%= t('all_decks.name') %></th>
    <th><%= t('all_decks.active') %></th>
    <th><%= t('all_decks.edit_deck') %></th>
    <th><%= t('all_decks.delete_deck') %></th>
  </tr>

  <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= deck.active %></td>

        <td><%= link_to t('all_decks.edit_deck'), edit_dashboard_deck_path(deck) %></td>
        <td><%= link_to t('all_decks.delete_deck'), dashboard_deck_path(deck.id),
                        method: :delete,
                        data: { confirm: t('all_decks.confirm') } %></td>
  <% end %>
  </tr>
</table>

app/views/dashboard/decks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-push-3 text-center ">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1><%= t('deck.new_deck') %></h1>
          <%= render 'form'%>
        </div>
      </div>
    </div>
  </div>
</div>