config/routes.rb
Rails.application.routes.draw do

  scope "/:locale" do
      namespace :dashboard do
        resources :decks
        resources :cards
        resources :home, only:[:index, :check]
      end
      namespace :home do
        resources :users
        resources :sessions, only: [:new, :create, :destroy]
      end
  end
  get 'oauths/oauth'

  get 'oauths/callback'


  root "dashboard/home#index"

  get 'logout' => 'home/sessions#destroy', as: 'logout'
  get 'login' => 'home/sessions#new', as: 'login'
  get 'signup' => 'home/users#new', as: 'signup'
  post 'login' => 'home/sessions#new'
  patch 'home' => 'home#check'
  get 'home', to: 'dashboard/home#index', defaults: { format: :json }
  post 'home', to: 'dashboard/home#check', defaults: { format: :json }
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callbck' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
end

app/views/layouts/_header.html.erb
<header class="clearfix">
  <h1><%= link_to t('app.flashcards'), root_path %></h1>

  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to t('app.all_cards'), dashboard_cards_path %></li>
    <% if current_user %>
    <li role="presentation"><%= link_to t('app.new_card'), new_dashboard_card_path %></li>
    <li role="presentation"><%= link_to t('app.new_deck'), new_dashboard_deck_path %></li>
    <li role="presentation"><%= link_to t('app.all_decks'), dashboard_decks_path %></li>
          <li><%= link_to t('app.settings'), edit_home_user_path(current_user) %></li>
          <li>
            <%= link_to t('app.log_out'), logout_path %>
          </li>
    <% else %>
        <li role="presentation"><%= link_to t('app.sign_in'), signup_path %></li>
        <li role="presentation"><%= link_to t('app.log_in'), login_path %></li>
        <li role="presentation"><%= link_to t('app.oauth_login'), auth_at_provider_path(:provider => :twitter) %></li>
        <li role="presentation">
          <% if I18n.locale == I18n.default_locale %>
              <%= link_to t('app.switch'), locale: 'en' %>
          <% else %>
              <%= link_to t('app.switch'), locale: 'ru' %>
          <% end %>
        </li>
    <% end %>

  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app.flashcards') %></title>
    <%= csrf_meta_tags %>
    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <script src='http://code.jquery.com/jquery.js'></script>
  </head>

  <body>
    <section id="container">
      <%= render 'layouts/header' %>
      <%= yield %>
    </section>
  </body>
</html>